### ISSUE TITLE
zsh: command not found: azure-cost

### ISSUE THREAD

**Issue by swapnavetcha** [mivano/azure-cost-cli#163]
Hi 

I have installed the cli using
% dotnet tool install --global azure-cost-cli 
Tool 'azure-cost-cli' is already installed.

when i run >azure-cost
it says >zsh: command not found: azure-cost

i tried with ./azure-cost --help still the same error

Im using mac 

kindly help

**Comment by mivano** [comment]
I cannot reproduce (using a Mac as well). So check with `dotnet tool list --global` if it is indeed listed.

And check if you are not running as a sudo user. So that it installs it somewhere else and not on your user path.

If that does not help; try uninstall `dotnet tool uninstall --global azure-cost-cli` and reinstall.

It might also be an issue with your path definition. It needs to have the tools folder there as well. Then you need to add `export PATH="$PATH:$HOME/.dotnet/tools/"`

See https://stackoverflow.com/questions/69894735/zsh-command-not-found-dotnet-ef
